### ISSUE TITLE
add suppoort for Fysect TFT EVE 5"

### ISSUE THREAD

**Issue by sl1pkn07** [RudolphRiedel/FT800-FT813#7]
Hi, i purchase this TFT for my 3dprinter

https://es.aliexpress.com/item/4000628057351.html?spm=a2g0s.9042311.0.0.a4c463c08gLTib

this display have a chipset

EBRT FT810Q
https://www.mouser.es/ProductDetail/Bridgetek/FT810Q-T
https://www.mouser.es/datasheet/2/880/DS_FT81x-1140609.pdf

i have test the examples as-sis (without touch the configuration) and "works"

![](https://user-images.githubusercontent.com/462213/79346981-55eee280-7f33-11ea-8601-738277ed4ba3.jpeg)

the only not works is the touch panel and emit a wreid sound from the speaker

is possible add this tft to you library?

greetings

you can see more info in https://github.com/MarlinFirmware/Marlin/issues/16628

**Comment by RudolphRiedel** [comment]
Try using EVE_RVT50, this should be very similar.
It says on Aliexpress that it is compatible with Luzbot CLCD so I can check if I can get the parameters for this one.
But without real information there is only so much one can try.
