### ISSUE TITLE
ESP32 not initializing if GPIO pin number > 31

### ISSUE THREAD

**Issue by Di-rk** [RudolphRiedel/FT800-FT813#89]
Hi,
On the ESP32 platform the EVE does not initialize correctly if a GPIO number is higher than 31.
For example: on my board, the EVE_PDN pin is set to pin 33 on the ESP32.
This can be fixed by changing the "BIT" macro in the EVE_init_spi function to "BIT64".

**Comment by RudolphRiedel** [comment]
Thank you for the report!
After fixing it and doing the commit/push I actually tried it now with GPIO_NUM_35 for PD and it works.

**Comment by Di-rk** [comment]
Looks good, thanks!
